[SupportedFields]
fanart
marquee
boxart
image
wheel
titleshot	

[ImageSource]
Screenshot=

[ThumbnailSource]
Box 2D=Box

[BoxArtSource]
Box 3D=Box_3D

[MarqueeSource]
Clear Logo=Logos
Marquee=Marquee

[WheelSource]
Clear Logo=Logos
Marquee=Marquee

[CartridgeSource]
Cartridge=Cart
Cartrige Top=CartTop
Cartridge 3D=Cart_3D
CD=CD
Disc=Disc

[Systems]
; You can add any missing or new systems
; This is a cross reference to rom folder name
3do=25
3ds=4912
advision=4974
amiga=4911
amiga1200=4911
amiga500=4911
amigacd32=4947
amstradcpc=4914
apfm1000=4969
apple2=4942
arcade=23
arcadia=4963
archimedes=4944
astrocde=4968
atari2600=22
atari5200=26
atari7800=27
atari800=4943
atarilynx=4924
atarijaguar=28
atarijaguarcd=29
atarist=4937
atom=5014
bbc=5013
boom3=1
c128=4946
c20=4945
c64=40
cave=23
cdi=4917
channelf=4928
coco=4941
colecovision=31
cplus4=5007
crvision=4998
doom3=1
dreamcast=16
electron=4954
fbneo=23
fds=4936
fm7=4978
fmtowns=4932
gameandwatch=4950
gamecom=4940
gamecube=2
gamegear=20
gb=4
gba=5
gbc=41
gp32=5015
gx4000=4999
halflife=1
hikaru=23
intellivision=32
jaguar=28
lindbergh=23
lynx=4924
macintosh=37
mame=23
mastersystem=35
megacd=21
megadrive=18
msx1=4929
msx2=4929
msx2+=4929
n64=3
nds=8
neogeo=24
neogeocd=4956
nes=7
ngp=4922
ngpc=4923
o2em=4927
pc88=4933
pc98=4934
pcengine=34
pcenginecd=4955
pcfx=4930
pet=5008
ps2=11
ps3=12
psp=13
psvita=39
psx=10
quake=1
quake2=1
rtcw=1
saturn=17
scv=4966
sega32x=33
segacd=21
sg1000=4949
snes=6
socrates=4998
supervision=4959
switch=4971
teknoparrot=23
ti99=4953
tutor=4960
turbografx16=34
turbografxcd=4955
tyrquake=1
vc4000=4994
vectrex=4939
virtualboy=4918
vsmile=4988
wii=9
wiiu=38
windows=1
wswan=4925
wswanc=4926
x68000=4931
xash3d_fwgs=1
xbox=14
xbox360=15
xboxlivearcade=15
z81=5010
zx81=5010
zxspectrum=4913
abuse=1
adam
amigacdtv
apple2gs
atomiswave=23
camplynx
cave3rd
cdogs
daphne=23
devilutionx=1
dos=1
ecwolf=1
gmaster
gzdoom=1
model2=23
model3=23
mugen
n64dd=3
namco2x6=23
naomi=23
naomi2=23
openbor
openlara=1
raze=1
reminiscence
scummvm=1
sgb
snes-msu1
spectravideo
steam=1
sufami
supergrafx
triforce=23
vpinball
xrick=1