//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamelistManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastScraper {
            get {
                return ((string)(this["LastScraper"]));
            }
            set {
                this["LastScraper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentFiles {
            get {
                return ((string)(this["RecentFiles"]));
            }
            set {
                this["RecentFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("batocera")]
        public string BatoceraHostName {
            get {
                return ((string)(this["BatoceraHostName"]));
            }
            set {
                this["BatoceraHostName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public string AlternatingRowColor {
            get {
                return ((string)(this["AlternatingRowColor"]));
            }
            set {
                this["AlternatingRowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConfirmBulkChange {
            get {
                return ((bool)(this["ConfirmBulkChange"]));
            }
            set {
                this["ConfirmBulkChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveReminder {
            get {
                return ((bool)(this["SaveReminder"]));
            }
            set {
                this["SaveReminder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxUndo {
            get {
                return ((int)(this["MaxUndo"]));
            }
            set {
                this["MaxUndo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCounts {
            get {
                return ((bool)(this["ShowCounts"]));
            }
            set {
                this["ShowCounts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wor")]
        public string Region {
            get {
                return ((string)(this["Region"]));
            }
            set {
                this["Region"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArcadeDB_Checkboxes {
            get {
                return ((string)(this["ArcadeDB_Checkboxes"]));
            }
            set {
                this["ArcadeDB_Checkboxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScreenScraper_Checkboxes {
            get {
                return ((string)(this["ScreenScraper_Checkboxes"]));
            }
            set {
                this["ScreenScraper_Checkboxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmuMovies_Checkboxes {
            get {
                return ((string)(this["EmuMovies_Checkboxes"]));
            }
            set {
                this["EmuMovies_Checkboxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MediaSources {
            get {
                return ((string)(this["MediaSources"]));
            }
            set {
                this["MediaSources"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int GridFontSize {
            get {
                return ((int)(this["GridFontSize"]));
            }
            set {
                this["GridFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VerifyDownloadedImages {
            get {
                return ((bool)(this["VerifyDownloadedImages"]));
            }
            set {
                this["VerifyDownloadedImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScrapeEnglishGenreOnly {
            get {
                return ((bool)(this["ScrapeEnglishGenreOnly"]));
            }
            set {
                this["ScrapeEnglishGenreOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Horizontal")]
        public string GridLineVisibility {
            get {
                return ((string)(this["GridLineVisibility"]));
            }
            set {
                this["GridLineVisibility"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFileStatusBar {
            get {
                return ((bool)(this["ShowFileStatusBar"]));
            }
            set {
                this["ShowFileStatusBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VideoAutoplay {
            get {
                return ((bool)(this["VideoAutoplay"]));
            }
            set {
                this["VideoAutoplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int Volume {
            get {
                return ((int)(this["Volume"]));
            }
            set {
                this["Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SearchDepth {
            get {
                return ((int)(this["SearchDepth"]));
            }
            set {
                this["SearchDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MamePath {
            get {
                return ((string)(this["MamePath"]));
            }
            set {
                this["MamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RememberColumns {
            get {
                return ((bool)(this["RememberColumns"]));
            }
            set {
                this["RememberColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RememberAutoSize {
            get {
                return ((bool)(this["RememberAutoSize"]));
            }
            set {
                this["RememberAutoSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSizeColumns {
            get {
                return ((bool)(this["AutoSizeColumns"]));
            }
            set {
                this["AutoSizeColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SuspendSortingInEditMode {
            get {
                return ((bool)(this["SuspendSortingInEditMode"]));
            }
            set {
                this["SuspendSortingInEditMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScrapeAnyMedia {
            get {
                return ((bool)(this["ScrapeAnyMedia"]));
            }
            set {
                this["ScrapeAnyMedia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoExpandLogger {
            get {
                return ((bool)(this["AutoExpandLogger"]));
            }
            set {
                this["AutoExpandLogger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{""image"":""images"",""titleshot"":""images"",""marquee"":""images"",""wheel"":""images"",""thumbnail"":""images"",""cartridge"":""images"",""video"":""videos"",""music"":""music"",""map"":""images"",""bezel"":""images"",""manual"":""manuals"",""fanart"":""images"",""boxart"":""images"",""boxback"":""images"",""magazine"":""images"",""mix"":""images""}")]
        public string MediaPaths {
            get {
                return ((string)(this["MediaPaths"]));
            }
            set {
                this["MediaPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"Description\": true, \"Developer\": false, \"Favorite\": false, \"Game Time\": false, " +
            "\"Language\": false, \"Last Played\": false, \"Play Count\": false, \"Publisher\": false" +
            ", \"Region\": false, \"Genre\": true, \"Rating\": true, \"Players\": true, \"Release Date" +
            "\": true}")]
        public string VisibleGridColumns {
            get {
                return ((string)(this["VisibleGridColumns"]));
            }
            set {
                this["VisibleGridColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"Description\": true, \"Developer\": false, \"Favorite\": false, \"Game Time\": false, " +
            "\"Language\": false, \"Last Played\": false, \"Play Count\": false, \"Publisher\": false" +
            ", \"Region\": false, \"Genre\": true, \"Rating\": true, \"Players\": true, \"Release Date" +
            "\": true}")]
        public string DefaultColumns {
            get {
                return ((string)(this["DefaultColumns"]));
            }
            set {
                this["DefaultColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\"USA (us)\",\"ScreenScraper (ss)\",\"Europe (eu)\",\"United Kingdom (uk)\",\"World (wor)" +
            "\"]")]
        public string Region_Fallback {
            get {
                return ((string)(this["Region_Fallback"]));
            }
            set {
                this["Region_Fallback"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
            set {
                this["Version"] = value;
            }
        }
    }
}
